from pathlib import Path
p = Path('app/src/main/java/com/example/giaohangpro/MainActivity.kt')
s = p.read_text()

needle = '''    // Tìm một khách theo id để màn hình chi tiết luôn lấy dữ liệu mới nhất.\n    fun findCustomer(id: Long): Customer? = customerState.firstOrNull { it.id == id }\n\n'''
if 'fun ensureCustomerFromImportedOrder(' not in s:
    block = '''    // Chuẩn hóa SĐT để so khớp khách cũ kể cả khi dữ liệu nhập dùng +84 / 84 / 0 hoặc có khoảng trắng.\n    private fun normalizeCustomerPhone(raw: String): String {\n        val digits = raw.filter(Char::isDigit)\n        return when {\n            digits.startsWith("0084") && digits.length > 4 -> "0" + digits.drop(4)\n            digits.startsWith("84") && digits.length >= 10 -> "0" + digits.drop(2)\n            else -> digits\n        }\n    }\n\n    // Tìm khách theo SĐT chính hoặc SĐT phụ. Không dùng tên vì tên trên đơn có thể thay đổi.\n    fun findCustomerByPhone(phone: String): Customer? {\n        val wanted = normalizeCustomerPhone(phone)\n        if (wanted.isBlank()) return null\n        return customerState.firstOrNull { customer ->\n            normalizeCustomerPhone(customer.phone) == wanted ||\n                customer.extraPhones.any { normalizeCustomerPhone(it.number) == wanted }\n        }\n    }\n\n    /**\n     * Dùng riêng khi nạp đơn hàng/VTMan.\n     * - Nếu SĐT đã tồn tại: trả khách cũ và TUYỆT ĐỐI không sửa bất kỳ trường nào.\n     * - Nếu SĐT chưa tồn tại: tạo khách mới từ tên + SĐT + địa chỉ; tọa độ để trống để người dùng bổ sung sau.\n     * Hàm này cố ý không gọi updateCustomer() cho khách cũ để bảo vệ tọa độ, ảnh, ghi chú, tên phụ,\n     * SĐT phụ, địa chỉ phụ và mọi dữ liệu người dùng đã lưu trước đó.\n     */\n    fun ensureCustomerFromImportedOrder(name: String, phone: String, address: String): Customer? {\n        val normalized = normalizeCustomerPhone(phone)\n        if (normalized.isBlank()) return null\n\n        findCustomerByPhone(phone)?.let { existing ->\n            return existing // QUAN TRỌNG: khách cũ chỉ đọc và trả về, không ghi đè.\n        }\n\n        val cleanName = name.trim().ifBlank { phone.trim() }\n        val cleanPhone = phone.trim()\n        val cleanAddress = address.trim()\n        val newId = (customerState.maxOfOrNull { it.id } ?: 0L) + 1L\n        val created = Customer(\n            id = newId,\n            name = cleanName,\n            phone = cleanPhone,\n            address = cleanAddress,\n            latitude = "",\n            longitude = "",\n            initials = createInitials(cleanName)\n        )\n        customerState.add(created)\n        return created\n    }\n\n'''
    if needle not in s:
        raise SystemExit('MainViewModel insertion point not found')
    s = s.replace(needle, needle + block, 1)

p.write_text(s)
