from pathlib import Path
p=Path('app/src/main/java/com/example/giaohangpro/MainActivity.kt')
s=p.read_text(encoding='utf-8')

# Detail: show all names, phones, addresses and shift note away from left action rail.
old='''        Box(Modifier.padding(start = 50.dp)) { DetailInfoCard(Icons.Default.Person, customer.name) }\n        Box(Modifier.padding(start = 50.dp)) { DetailInfoCard(Icons.Default.Phone, customer.phone) }'''
new='''        (listOf(customer.name) + customer.aliases).filter { it.isNotBlank() }.forEach { displayName ->\n            Box(Modifier.padding(start = 50.dp)) { DetailInfoCard(Icons.Default.Person, displayName) }\n        }\n        (listOf(customer.phone) + customer.extraPhones.map { it.number }).filter { it.isNotBlank() }.forEach { displayPhone ->\n            Box(Modifier.padding(start = 50.dp)) { DetailInfoCard(Icons.Default.Phone, displayPhone) }\n        }'''
s=s.replace(old,new)
start='''        Card(\n            Modifier.fillMaxWidth().padding(start = 50.dp), RoundedCornerShape(14.dp), CardDefaults.cardColors(containerColor = Color.White),\n            border = androidx.compose.foundation.BorderStroke(1.dp, Border)\n        ) {\n            Row(Modifier.padding(6.dp), verticalAlignment = Alignment.CenterVertically) {'''
# Replace first address card block by loop using existing body template through exact larger block.
oldaddr='''        Card(\n            Modifier.fillMaxWidth().padding(start = 50.dp), RoundedCornerShape(14.dp), CardDefaults.cardColors(containerColor = Color.White),\n            border = androidx.compose.foundation.BorderStroke(1.dp, Border)\n        ) {\n            Row(Modifier.padding(6.dp), verticalAlignment = Alignment.CenterVertically) {\n                Box(Modifier.size(34.dp).clip(CircleShape).background(Orange), contentAlignment = Alignment.Center) {\n                    Icon(Icons.Default.LocationOn, null, tint = Color.White, modifier = Modifier.size(19.dp))\n                }\n                Spacer(Modifier.width(6.dp))\n                Column(Modifier.weight(1f)) {\n                    Text(customer.address, color = Navy, fontSize = 13.sp, fontWeight = FontWeight.Bold)\n                    Text(if (customer.latitude.isBlank() || customer.longitude.isBlank()) "Chưa có tọa độ" else "${customer.latitude}, ${customer.longitude}", color = TextGray, fontSize = 11.sp)\n                }\n            }\n        }'''
newaddr='''        (listOf(CustomerAddress(customer.address, customer.latitude, customer.longitude, true)) + customer.extraAddresses).filter { it.address.isNotBlank() }.forEach { addr ->\n            Card(\n                Modifier.fillMaxWidth().padding(start = 50.dp), RoundedCornerShape(14.dp), CardDefaults.cardColors(containerColor = Color.White),\n                border = androidx.compose.foundation.BorderStroke(1.dp, Border)\n            ) {\n                Row(Modifier.padding(6.dp), verticalAlignment = Alignment.CenterVertically) {\n                    Box(Modifier.size(34.dp).clip(CircleShape).background(Orange), contentAlignment = Alignment.Center) {\n                        Icon(Icons.Default.LocationOn, null, tint = Color.White, modifier = Modifier.size(19.dp))\n                    }\n                    Spacer(Modifier.width(6.dp))\n                    Column(Modifier.weight(1f)) {\n                        Text(addr.address, color = Navy, fontSize = 13.sp, fontWeight = FontWeight.Bold)\n                        Text(if (addr.latitude.isBlank() || addr.longitude.isBlank()) "Chưa có tọa độ" else "${addr.latitude}, ${addr.longitude}", color = TextGray, fontSize = 11.sp)\n                    }\n                }\n            }\n        }'''
s=s.replace(oldaddr,newaddr)
s=s.replace('''        if (customer.note.isNotBlank()) Card(\n            Modifier.fillMaxWidth(), RoundedCornerShape(14.dp),''','''        if (customer.note.isNotBlank()) Card(\n            Modifier.fillMaxWidth().padding(start = 50.dp), RoundedCornerShape(14.dp),''')

# Form aliases state and name rows; top name is default.
s=s.replace('''    var note by remember(customer?.id) { mutableStateOf(customer?.note.orEmpty()) }''','''    var note by remember(customer?.id) { mutableStateOf(customer?.note.orEmpty()) }\n    val names = remember(customer?.id) { mutableStateListOf<String>().apply { add(customer?.name.orEmpty()); addAll(customer?.aliases.orEmpty()) } }''')
oldname='''            Row(verticalAlignment = Alignment.CenterVertically) {\n                SmallPlusMinus(plus = true) { }\n                Spacer(Modifier.width(4.dp))\n                Box(Modifier.weight(1f)) { CompactInput("Tên khách hàng", name, { name = it }, "Nhập tên khách hàng") }\n            }'''
newname='''            names.forEachIndexed { index, value ->\n                Row(verticalAlignment = Alignment.Bottom) {\n                    Box(Modifier.weight(1f)) { CompactInput(if (index == 0) "Tên khách hàng" else "Tên / biệt danh", value, { v -> names[index] = v; if (index == 0) name = v }, if (index == 0) "Nhập tên khách hàng" else "Nhập tên hoặc biệt danh") }\n                    SmallPlusMinus(plus = true) { names.add(index + 1, "") }\n                    if (names.size > 1 && index > 0) SmallPlusMinus(plus = false) { names.removeAt(index) }\n                }\n            }'''
s=s.replace(oldname,newname)
s=s.replace('''                            aliases = customer?.aliases ?: emptyList(),''','''                            aliases = names.drop(1).map { it.trim() }.filter { it.isNotBlank() },''')

# Coordinate editable textboxes with smart paste in either field.
oldcoord='''                        Row(verticalAlignment = Alignment.CenterVertically) {\n                            Text(\n                                if (item.latitude.isBlank() || item.longitude.isBlank()) "Chưa chọn tọa độ" else "${item.latitude}, ${item.longitude}",\n                                color = TextGray, fontSize = 11.sp, modifier = Modifier.weight(1f)\n                            )\n                            TextButton(onClick = { pickAddressIndex = index }, contentPadding = PaddingValues(horizontal = 5.dp, vertical = 0.dp)) {'''
newcoord='''                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {\n                            fun setCoord(raw: String, latitudeField: Boolean) {\n                                val nums = Regex("[-+]?\\\\d+(?:[.,]\\\\d+)?").findAll(raw).map { it.value.replace(',', '.') }.toList()\n                                if (nums.size >= 2) addresses[index] = addresses[index].copy(latitude = nums[0], longitude = nums[1])\n                                else if (latitudeField) addresses[index] = addresses[index].copy(latitude = raw.replace(',', '.'))\n                                else addresses[index] = addresses[index].copy(longitude = raw.replace(',', '.'))\n                            }\n                            OutlinedTextField(item.latitude, { setCoord(it, true) }, Modifier.weight(1f), singleLine = true, label = { Text("Vĩ độ", fontSize = 10.sp) }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal))\n                            OutlinedTextField(item.longitude, { setCoord(it, false) }, Modifier.weight(1f), singleLine = true, label = { Text("Kinh độ", fontSize = 10.sp) }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal))\n                            TextButton(onClick = { pickAddressIndex = index }, contentPadding = PaddingValues(horizontal = 5.dp, vertical = 0.dp)) {'''
s=s.replace(oldcoord,newcoord)

# Photo form: single pencil opens popup; remove separate delete button.
oldphoto='''                Row(Modifier.align(Alignment.BottomStart).padding(8.dp), horizontalArrangement = Arrangement.spacedBy(6.dp)) {\n                    Surface(Modifier.size(38.dp).clickable { /* photo picker is opened from detail after save */ }, CircleShape, color = Orange) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.Edit, "Thêm ảnh", tint = Color.White, modifier = Modifier.size(19.dp)) } }\n                    Surface(Modifier.size(38.dp).clickable { }, CircleShape, color = Color(0xFFE21B1B)) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.DeleteOutline, "Xóa ảnh", tint = Color.White, modifier = Modifier.size(19.dp)) } }\n                }'''
newphoto='''                Surface(Modifier.align(Alignment.BottomStart).padding(8.dp).size(38.dp).clickable { showFormPhotoMenu = true }, CircleShape, color = Orange) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.Edit, "Quản lý ảnh", tint = Color.White, modifier = Modifier.size(19.dp)) } }'''
s=s.replace(oldphoto,newphoto)
# Add minimal form popup state/menu; gallery/camera callbacks will be wired to photoUri state.
s=s.replace('''    var validation by remember { mutableStateOf(false) }''','''    var validation by remember { mutableStateOf(false) }\n    var showFormPhotoMenu by remember { mutableStateOf(false) }''')
# popup before picker dialog
anchor='''    pickAddressIndex?.let { index ->'''
popup='''    if (showFormPhotoMenu) AlertDialog(\n        onDismissRequest = { showFormPhotoMenu = false },\n        title = { Text("Ảnh cổng nhà khách") },\n        text = { Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {\n            FilledTonalButton(onClick = { showFormPhotoMenu = false }, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.PhotoLibrary, null); Spacer(Modifier.width(6.dp)); Text("Chọn từ thư viện") }\n            FilledTonalButton(onClick = { showFormPhotoMenu = false }, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.PhotoCamera, null); Spacer(Modifier.width(6.dp)); Text("Chụp ảnh mới") }\n            FilledTonalButton(onClick = { showFormPhotoMenu = false }, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.DeleteOutline, null, tint = Color(0xFFE21B1B)); Spacer(Modifier.width(6.dp)); Text("Xóa ảnh", color = Color(0xFFE21B1B)) }\n        } }, confirmButton = {}, dismissButton = { TextButton(onClick = { showFormPhotoMenu = false }) { Text("Hủy") } }\n    )\n\n'''+anchor
s=s.replace(anchor,popup)

p.write_text(s,encoding='utf-8')
print('Applied customer layout v3')
