from pathlib import Path
p=Path('app/src/main/java/com/example/giaohangpro/MainActivity.kt')
s=p.read_text(encoding='utf-8')

# Better camera quality: replace thumbnail TakePicturePreview with full-size TakePicture into app cache.
s=s.replace('''    val cameraLauncher = rememberLauncherForActivityResult(ActivityResultContracts.TakePicturePreview()) { bitmap ->\n        bitmap ?: return@rememberLauncherForActivityResult\n        runCatching {\n            val file = java.io.File(context.filesDir, "customer_gate_${customer.id}.jpg")\n            java.io.FileOutputStream(file).use { out ->\n                bitmap.compress(android.graphics.Bitmap.CompressFormat.JPEG, 92, out)\n            }\n            onPhotoChanged(android.net.Uri.fromFile(file).toString())\n        }.onFailure {\n            Toast.makeText(context, "Không lưu được ảnh vừa chụp", Toast.LENGTH_SHORT).show()\n        }\n    }''','''    var pendingCameraUri by remember { mutableStateOf<android.net.Uri?>(null) }\n    val cameraLauncher = rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()) { ok ->\n        if (ok) pendingCameraUri?.let { onPhotoChanged(it.toString()) }\n    }''')
s=s.replace('''onClick = { showPhotoMenu = false; cameraLauncher.launch(null) }''','''onClick = {\n                        showPhotoMenu = false\n                        val file = java.io.File(context.filesDir, "customer_gate_${customer.id}_${System.currentTimeMillis()}.jpg")\n                        val uri = androidx.core.content.FileProvider.getUriForFile(context, context.packageName + ".fileprovider", file)\n                        pendingCameraUri = uri\n                        cameraLauncher.launch(uri)\n                    }''')

# Detail: remove pencil from photo, reserve left action rail and move info cards right.
s=s.replace('''                modifier = Modifier.fillMaxSize().padding(start = 4.dp, end = 4.dp, top = 3.dp, bottom = 3.dp),\n                onEditPhoto = { showPhotoMenu = true }''','''                modifier = Modifier.fillMaxSize().padding(start = 4.dp, end = 4.dp, top = 3.dp, bottom = 3.dp)''')
s=s.replace('''private fun CustomerDetailContent(\n    customer: Customer,\n    modifier: Modifier = Modifier,\n    onEditPhoto: () -> Unit\n)''','''private fun CustomerDetailContent(\n    customer: Customer,\n    modifier: Modifier = Modifier\n)''')
# Remove floating pencil surface inside photo.
needle='''                Surface(\n                    modifier = Modifier.align(Alignment.BottomStart).padding(12.dp).size(48.dp).clickable { onEditPhoto() },\n                    shape = CircleShape,\n                    color = Orange,\n                    shadowElevation = 4.dp\n                ) {\n                    Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {\n                        Icon(Icons.Default.Edit, "Thêm hoặc đổi ảnh", tint = Color.White, modifier = Modifier.size(24.dp))\n                    }\n                }\n'''
s=s.replace(needle,'')
# Shift info cards right by 50dp, photo stays full width.
s=s.replace('''        DetailInfoCard(Icons.Default.Person, customer.name)\n        DetailInfoCard(Icons.Default.Phone, customer.phone)''','''        Box(Modifier.padding(start = 50.dp)) { DetailInfoCard(Icons.Default.Person, customer.name) }\n        Box(Modifier.padding(start = 50.dp)) { DetailInfoCard(Icons.Default.Phone, customer.phone) }''')
s=s.replace('''        Card(\n            Modifier.fillMaxWidth(), RoundedCornerShape(14.dp), CardDefaults.cardColors(containerColor = Color.White),\n            border = androidx.compose.foundation.BorderStroke(1.dp, Border)\n        ) {\n            Row(Modifier.padding(6.dp), verticalAlignment = Alignment.CenterVertically) {\n                Box(Modifier.size(34.dp).clip(CircleShape).background(Orange), contentAlignment = Alignment.Center) {\n                    Icon(Icons.Default.LocationOn, null, tint = Color.White, modifier = Modifier.size(19.dp))''','''        Card(\n            Modifier.fillMaxWidth().padding(start = 50.dp), RoundedCornerShape(14.dp), CardDefaults.cardColors(containerColor = Color.White),\n            border = androidx.compose.foundation.BorderStroke(1.dp, Border)\n        ) {\n            Row(Modifier.padding(6.dp), verticalAlignment = Alignment.CenterVertically) {\n                Box(Modifier.size(34.dp).clip(CircleShape).background(Orange), contentAlignment = Alignment.Center) {\n                    Icon(Icons.Default.LocationOn, null, tint = Color.White, modifier = Modifier.size(19.dp))''',1)
# Action block begins directly below photo and fills vertical rail instead of bottom cluster.
s=s.replace('''modifier = Modifier.align(Alignment.BottomStart).padding(start = 3.dp, bottom = 3.dp),''','''modifier = Modifier.align(Alignment.TopStart).padding(start = 3.dp, top = 312.dp, bottom = 3.dp),''',1)
s=s.replace('''    Column(modifier, verticalArrangement = Arrangement.spacedBy(3.dp)) {''','''    Column(modifier, verticalArrangement = Arrangement.spacedBy(5.dp)) {''',1)
s=s.replace('''modifier = Modifier.size(width = 43.dp, height = 36.dp).clickable { onClick() },''','''modifier = Modifier.size(width = 45.dp, height = 42.dp).clickable { onClick() },''',1)

# Form: photo edit/delete buttons under lower-left of photo card.
s=s.replace('''            CustomerPhotoCard()\n            CompactInput("Tên khách hàng", name, { name = it }, "Nhập tên khách hàng")''','''            Box {\n                CustomerPhotoCard()\n                Row(Modifier.align(Alignment.BottomStart).padding(8.dp), horizontalArrangement = Arrangement.spacedBy(6.dp)) {\n                    Surface(Modifier.size(38.dp).clickable { /* photo picker is opened from detail after save */ }, CircleShape, color = Orange) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.Edit, "Thêm ảnh", tint = Color.White, modifier = Modifier.size(19.dp)) } }\n                    Surface(Modifier.size(38.dp).clickable { }, CircleShape, color = Color(0xFFE21B1B)) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.DeleteOutline, "Xóa ảnh", tint = Color.White, modifier = Modifier.size(19.dp)) } }\n                }\n            }\n            CompactInput("Tên khách hàng", name, { name = it }, "Nhập tên khách hàng")''')
# Hide 'Chính' labels, keep checkbox only.
s=s.replace('''                            Text("Chính", fontSize = 11.sp)\n                            Spacer(Modifier.width(3.dp))''','''                            Spacer(Modifier.width(3.dp))''')
# Phone dropdown icon visually inside text field by negative-ish compact spacing: reduce separate button and place overlay-like adjacent.
s=s.replace('''                            IconButton(onClick = { expandedPhone = if (expandedPhone == index) null else index }, modifier = Modifier.size(38.dp)) {''','''                            IconButton(onClick = { expandedPhone = if (expandedPhone == index) null else index }, modifier = Modifier.size(30.dp)) {''')
# Add plus before customer name for aliases (UI entry point; aliases already exist in model).
s=s.replace('''            CompactInput("Tên khách hàng", name, { name = it }, "Nhập tên khách hàng")''','''            Row(verticalAlignment = Alignment.CenterVertically) {\n                SmallPlusMinus(plus = true) { }\n                Spacer(Modifier.width(4.dp))\n                Box(Modifier.weight(1f)) { CompactInput("Tên khách hàng", name, { name = it }, "Nhập tên khách hàng") }\n            }''')

p.write_text(s,encoding='utf-8')
print('Applied customer detail/form layout v2')
